export const REGISTER = 'REGISTER'
export const LOGIN= 'LOGIN'
export const GET_PROPERTIES = 'GET_PROPERTIES'
export const ADD_PROPERTY = 'ADD_PROPERTY'
export const EDIT_PROPERTY = 'EDIT_PROPERTY'
export const DELETE_PROPERTY = 'DELETE_PROPERTY'
export const GET_ADMIN = "GET_ADMIN"